import { Press_Start_2P } from "next/font/google";
import "../styles/globals.css";

const pressStart = Press_Start_2P({
	variable: "--font-press-start",
	weight: "400",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${pressStart.variable}`}>{children}</body>
		</html>
	);
}
